/**
 * The commitment digest, checked against the shared fixture.
 *
 * The counterpart is `contracts/test/differential/Digest.t.sol`, which reads the same file and
 * recomputes the same values with `keccak256(abi.encode(...))`. Paper Appendix B makes this a
 * cross-language contract: if the encodings ever diverge, every honest challenge fails, and the
 * failure is silent because a digest mismatch looks exactly like a dishonest publisher.
 *
 * **This fixture was generated by the Python reference at 50 significant digits and is committed**,
 * so the TypeScript implementation is verified against the fixture rather than against the
 * implementation it is replacing. That is what makes the port a port rather than a rewrite with a new
 * source of truth.
 */

import { readFileSync } from 'node:fs';

import { keccak_256 } from '@noble/hashes/sha3.js';
import { describe, expect, it } from 'vitest';

import {
  commitmentDigest,
  commitmentPreimage,
  inputsHash,
  inputsPreimage,
  nameId,
} from '../../src/domain/digest.js';
import { bytesFromHex, hexOf } from '../../src/domain/bytes.js';
import { Symbol, type SessionKind } from '../../src/domain/models.js';

interface DigestCase {
  label: string;
  symbol: string;
  nameId: string;
  /**
   * A **string**, not a number, and this is load-bearing rather than stylistic.
   *
   * `forSession` is a uint64 and the boundary case is uint64 max, which exceeds JavaScript's
   * `Number.MAX_SAFE_INTEGER` (2^53 - 1). `JSON.parse` reads `18446744073709551615` as
   * `18446744073709552000` — exactly 2^64 — so the boundary case would arrive as an *out-of-range*
   * value rather than as a wrong digest, and the failure would point at the range check instead of at
   * the encoding. The fixture emits it as a string for that reason, alongside `lambdaWad` and
   * `premiumWad`, which are strings for the same class of reason at 256 bits.
   */
  forSession: string;
  sessionCode: SessionKind;
  windowSessions: number;
  sourceIds: string[];
  rowCount: number;
  rowsDigest: string;
  lambdaWad: string;
  premiumWad: string;
  inputsHash: string;
  digest: string;
  preimageLength: number;
}

interface DigestFixture {
  cases: DigestCase[];
  caseCount: number;
}

const fixture: DigestFixture = JSON.parse(
  readFileSync(new URL('../../../spec/digest.json', import.meta.url), 'utf8'),
) as DigestFixture;

const referenceKeccak = (data: Uint8Array): Uint8Array => keccak_256(data);

describe('the digest fixture', () => {
  it('is the size it says it is', () => {
    expect(fixture.cases.length).toBe(fixture.caseCount);
    expect(fixture.cases.length).toBeGreaterThan(0);
  });
});

describe('commitmentDigest', () => {
  it.each(fixture.cases)('matches the fixture: $label', (testCase) => {
    const computed = commitmentDigest(
      referenceKeccak,
      bytesFromHex(testCase.nameId),
      BigInt(testCase.forSession),
      BigInt(testCase.lambdaWad),
      BigInt(testCase.premiumWad),
      bytesFromHex(testCase.inputsHash),
    );
    expect(`0x${hexOf(computed)}`).toBe(testCase.digest);
  });
});

describe('inputsHash', () => {
  it.each(fixture.cases)('matches the fixture: $label', (testCase) => {
    const computed = inputsHash(
      referenceKeccak,
      testCase.windowSessions,
      testCase.sessionCode,
      testCase.sourceIds,
      testCase.rowCount,
      bytesFromHex(testCase.rowsDigest),
    );
    expect(`0x${hexOf(computed)}`).toBe(testCase.inputsHash);
  });
});

describe('nameId', () => {
  it.each(fixture.cases)('matches the fixture: $label', (testCase) => {
    const computed = nameId(referenceKeccak, new Symbol(testCase.symbol));
    expect(`0x${hexOf(computed)}`).toBe(testCase.nameId);
  });
});

describe('commitmentPreimage', () => {
  it.each(fixture.cases)('is five 32-byte words: $label', (testCase) => {
    const preimage = commitmentPreimage(
      bytesFromHex(testCase.nameId),
      BigInt(testCase.forSession),
      BigInt(testCase.lambdaWad),
      BigInt(testCase.premiumWad),
      bytesFromHex(testCase.inputsHash),
    );
    expect(preimage.length).toBe(testCase.preimageLength);
    expect(preimage.length).toBe(160);
  });
});

describe('the inputs serialisation', () => {
  it('cannot be confused by source splits', () => {
    // Length-prefixing the source identifiers is what prevents this collision. Without it a publisher
    // could commit one input set and be challenged against another.
    const digest = new Uint8Array(32);
    const joined = inputsPreimage(126, 'W', ['AB', 'C'], 10, digest);
    const split = inputsPreimage(126, 'W', ['A', 'BC'], 10, digest);
    expect(hexOf(joined)).not.toBe(hexOf(split));
  });
});
